apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: flux-operator-dashboards
    files:
      - dashboards/flux-control-plane.json
      - dashboards/flux-kubernetes-api.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
