---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: helmreleases
  namespace: benchmark
  labels:
    app.kubernetes.io/component: benchmark
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 12h
    fluxcd.controlplane.io/reconcileTimeout: 20m
    fluxcd.controlplane.io/reconcile: enabled
spec:
  wait: false
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app.kubernetes.io/component: benchmark
  commonMetadata:
    labels:
      sharding.fluxcd.io/key: apps
  resourcesTemplate: |
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    metadata:
      name: hrapp-chart
      namespace: << inputs.provider.namespace >>
    spec:
      interval: 1h
      url: oci://ghcr.io/stefanprodan/charts/podinfo
      ref:
        semver: << inputs.version >>
    ---
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    metadata:
      name: hrapp-chart-canary
      namespace: << inputs.provider.namespace >>
    spec:
      interval: 1h
      url: oci://ghcr.io/stefanprodan/charts/podinfo
      ref:
        semver: << inputs.canaryVersion >>
    <<- range $i := until (int inputs.objects) >>
    <<- $id := add $i 1 >>
    <<- $name := printf "hrapp-%04d" $id >>
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: << $name >>
      namespace: << inputs.provider.namespace >>
    data:
      values.yaml: |
        ui:
          color: "<< inputs.ui.color >>"
    ---
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: << $name >>
      namespace: << inputs.provider.namespace >>
    spec:
      interval: << inputs.interval | quote >>
      serviceAccountName: flux-operator
      chartRef:
        kind: OCIRepository
        name: << if lt $i 50 >>hrapp-chart-canary<< else >>hrapp-chart<< end >>
      driftDetection:
        mode: enabled
      values:
        replicaCount: 0
        ui:
          message: "<< inputs.ui.message >>"
      valuesFrom:
      - kind: ConfigMap
        name: << $name >>
    <<- end >>
