---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSetInputProvider
metadata:
  name: input
  namespace: benchmark
  labels:
    app.kubernetes.io/component: benchmark
spec:
  type: Static
  defaultValues:
    objects: 100
    interval: 30m
    replicaCount: 0
    ui:
      message: "benchmark-placeholder"
      color: "#34577c"
