---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: kustomizations
  namespace: benchmark
  labels:
    app.kubernetes.io/component: benchmark
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 12h
    fluxcd.controlplane.io/reconcileTimeout: 20m
    fluxcd.controlplane.io/reconcile: enabled
spec:
  wait: true
  dependsOn:
    - apiVersion: fluxcd.controlplane.io/v1
      kind: ResourceSet
      name: sources
      namespace: benchmark
      ready: true
      readyExpr: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app.kubernetes.io/component: benchmark
  commonMetadata:
    labels:
      sharding.fluxcd.io/key: apps
  resourcesTemplate: |
    <<- range $i := until (int inputs.objects) >>
    <<- $id := add $i 1 >>
    <<- $name := printf "ksapp-%04d" $id >>
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: << $name >>
      namespace: << inputs.provider.namespace >>
    data:
      color: "<< inputs.ui.color >>"
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << $name >>
      namespace: << inputs.provider.namespace >>
    spec:
      interval: << inputs.interval | quote >>
      wait: true
      targetNamespace: << inputs.provider.namespace >>
      serviceAccountName: flux-operator
      retryInterval: 5m
      timeout: 3m
      prune: true
      namePrefix: << $name >>-
      path: ./
      sourceRef:
        kind: OCIRepository
        name: << if lt $i 50 >>ksapp-manifests-canary<< else >>ksapp-manifests<< end >>
      postBuild:
        substituteFrom:
          - kind: ConfigMap
            name: << $name >>
      patches:
        - target:
            kind: Service
          patch: |-
            - op: replace
              path: /spec/selector/app
              value: << $name >>-podinfo
    <<- if gt inputs.replicaCount 0 >>
        - target:
            kind: HorizontalPodAutoscaler
          patch: |-
            - op: replace
              path: /spec/minReplicas
              value: << inputs.replicaCount | int >>
            - op: replace
              path: /spec/maxReplicas
              value: << inputs.replicaCount | int >>
    <<- end >>
        - target:
            kind: Deployment
          patch: |-
            - op: add
              path: /spec/replicas
              value: << inputs.replicaCount | int >>
            - op: replace
              path: /spec/selector/matchLabels/app
              value: << $name >>-podinfo
            - op: replace
              path: /spec/template/metadata/labels/app
              value: << $name >>-podinfo
            - op: add
              path: /spec/template/spec/containers/0/env/-
              value:
                name: PODINFO_UI_MESSAGE
                value: "<< inputs.ui.message >>"
            - op: replace
              path: /spec/template/spec/containers/0/resources
              value:
                requests:
                  cpu: 1m
                  memory: 16Mi
            - op: add
              path: /spec/template/spec/affinity
              value:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                      - matchExpressions:
                          - key: app.fluxcd.io/role
                            operator: In
                            values:
                              - benchmark
            - op: add
              path: /spec/template/spec/tolerations
              value:
                - effect: NoSchedule
                  key: app.fluxcd.io/role
                  operator: Equal
                  value: benchmark
    <<- end >>
