---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: kustomizations
  namespace: benchmark
  labels:
    app.kubernetes.io/component: benchmark
  annotations:
    fluxcd.controlplane.io/reconcileEvery: 12h
    fluxcd.controlplane.io/reconcileTimeout: 20m
    fluxcd.controlplane.io/reconcile: enabled
spec:
  wait: false
  inputsFrom:
    - kind: ResourceSetInputProvider
      selector:
        matchLabels:
          app.kubernetes.io/component: benchmark
  commonMetadata:
    labels:
      sharding.fluxcd.io/key: apps
  resourcesTemplate: |
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    metadata:
      name: ksapp-manifests
      namespace: << inputs.provider.namespace >>
    spec:
      interval: 1h
      url: oci://ghcr.io/stefanprodan/manifests/podinfo
      ref:
        semver: "<< inputs.version >>"
    ---
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: OCIRepository
    metadata:
      name: ksapp-manifests-canary
      namespace: << inputs.provider.namespace >>
    spec:
      interval: 1h
      url: oci://ghcr.io/stefanprodan/manifests/podinfo
      ref:
        semver: "<< inputs.canaryVersion >>"
    <<- range $i := until (int inputs.objects) >>
    <<- $id := add $i 1 >>
    <<- $name := printf "ksapp-%04d" $id >>
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: << $name >>
      namespace: << inputs.provider.namespace >>
    data:
      color: "<< inputs.ui.color >>"
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: << $name >>
      namespace: << inputs.provider.namespace >>
    spec:
      interval: << inputs.interval | quote >>
      wait: true
      targetNamespace: << inputs.provider.namespace >>
      serviceAccountName: flux-operator
      retryInterval: 5m
      timeout: 3m
      prune: true
      namePrefix: << $name >>-
      path: ./
      sourceRef:
        kind: OCIRepository
        name: << if lt $i 50 >>ksapp-manifests-canary<< else >>ksapp-manifests<< end >>
      postBuild:
        substituteFrom:
          - kind: ConfigMap
            name: << $name >>
      patches:
        - target:
            kind: Service
          patch: |-
            - op: replace
              path: /spec/selector/app
              value: << $name >>-podinfo
        - target:
            kind: Deployment
          patch: |-
            - op: replace
              path: /spec/selector/matchLabels/app
              value: << $name >>-podinfo
            - op: replace
              path: /spec/template/metadata/labels/app
              value: << $name >>-podinfo
            - op: add
              path: /spec/replicas
              value: 0
            - op: add
              path: /spec/template/spec/containers/0/env/-
              value:
                name: PODINFO_UI_MESSAGE
                value: "<< inputs.ui.message >>"
    <<- end >>
