---
apiVersion: v1
kind: Namespace
metadata:
  name: benchmark
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-operator
  namespace: benchmark
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-operator-benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flux-operator
    namespace: benchmark
