{
 "title": "Flux Operator Performance",
 "tags": [ "flux" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "workqueue_work_duration_seconds_count"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, flux_instance_info{kind=\"FluxInstance\"})",
     "legendFormat": "Flux {{revision}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "topk(1,kubernetes_build_info)", "legendFormat": "Kubernetes {{git_version}}" }
   ]
  },
  {
   "title": "Active Reconciliations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{namespace=\"$namespace\"}[5m])) + sum(controller_runtime_active_workers{namespace=\"$namespace\"})",
     "legendFormat": "reconciliations"
    }
   ]
  },
  {
   "title": "Queued Reconciliations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(workqueue_depth{namespace=\"$namespace\"})",
     "legendFormat": "reconciliations"
    }
   ]
  },
  {
   "title": "Scheduled Reconciliations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flux_resource_info) + count(flux_resourceset_info)",
     "legendFormat": "resources"
    }
   ]
  },
  {
   "title": "Kubernetes API Server req/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\"}[5m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Max Reconcile Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(controller_runtime_reconcile_time_seconds_sum{namespace=\"$namespace\"}[15m]) / rate(controller_runtime_reconcile_time_seconds_count{namespace=\"$namespace\"}[15m]))\n\n",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Max Queue Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(workqueue_longest_running_processor_seconds{namespace=\"$namespace\"})",
     "legendFormat": "seconds"
    }
   ]
  },
  {
   "title": "Flux Kuberentes API Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(apiserver_request_total{component=\"apiserver\",group=~\".*flux.*\"}[5m])) / sum(rate(apiserver_request_total{component=\"apiserver\"}[5m]))) * 100",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Flux Drift Detection req/sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\",dry_run=\"All\"}[5m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Flux Controllers Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"manager\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container=\"manager\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Flux CPU Usage by Controller",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (namespace,pod,container) (rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container=\"manager\"}[5m])) \n  / on(namespace,pod,container) \n  group_left sum by (namespace,pod,container) (kube_pod_container_resource_limits{resource=\"cpu\",namespace=\"$namespace\"})\n) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flux Memory Usage by Controller",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{namespace=\"flux-system\",container=\"manager\"} / on(namespace,pod,container) kube_pod_container_resource_limits{resource=\"memory\",namespace=\"flux-system\"}) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flux Goroutines by Controller",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flux Open File Descriptors by Controller",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\"}\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "core(s)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{service=\"kubernetes\"}[5m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_memory_classes_total_bytes{service=\"kubernetes\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Kubernetes API Server CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(process_cpu_seconds_total{service=\"kubernetes\"}[5m])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kubernetes API Server Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memory_classes_total_bytes{service=\"kubernetes\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes API Server req/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"apiserver\"}[5m])) by (verb)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Flux Reconciliation Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Flux Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flux Workqueue",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((workqueue_depth{namespace=\"$namespace\"})) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flux API Requests by Controller",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flux API Requests by Method ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flux API Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",code!~\"2..\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Flux Reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Flux Operator req/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",pod=~\".*operator.*\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flux Operator Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(flux_resourceset_info)", "legendFormat": "resources" }
   ]
  },
  {
   "title": "Flux Kustomize Controller req/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",pod=~\".*kustomize.*\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kustomization Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flux_resource_info{kind=\"Kustomization\"})",
     "legendFormat": "resources"
    }
   ]
  },
  {
   "title": "Flux Helm Controller req/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{namespace=\"$namespace\",pod=~\".*helm.*\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HelmRelease Resources",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 98 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flux_resource_info{kind=\"HelmRelease\"})",
     "legendFormat": "resources"
    }
   ]
  }
 ]
}